spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/zach}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200}
